from __future__ import annotations
import argparse, json, html, shutil, base64, mimetypes, copy
from pathlib import Path
from common import ROOT, load_json

def esc(s): return html.escape(str(s or ''),quote=True)

def _self_contain_runtime(rt):
    rt=copy.deepcopy(rt)
    for project in rt.get('projects',[]):
        logo=project.get('logo')
        if logo and logo.startswith('assets/'):
            fp=ROOT/logo
            if fp.exists():
                mime=mimetypes.guess_type(fp.name)[0] or 'application/octet-stream'
                project['logo']='data:'+mime+';base64,'+base64.b64encode(fp.read_bytes()).decode('ascii')
        for media in project.get('media',[]):
            src=media.get('src','')
            if media.get('type')=='image' and src.startswith('../'):
                fp=ROOT/src[3:]
                if fp.exists():
                    mime=mimetypes.guess_type(fp.name)[0] or 'application/octet-stream'
                    media['src']='data:'+mime+';base64,'+base64.b64encode(fp.read_bytes()).decode('ascii')
            elif media.get('type')=='iframe' and src.startswith('../'):
                rel=src[3:]; path,_,query=rel.partition('?'); fp=ROOT/path
                if fp.exists():
                    doc=fp.read_text(encoding='utf-8')
                    if 'state=security' in query:
                        doc=doc.replace('<div class="popover" id="security">','<div class="popover open" id="security">')
                    if 'state=folder' in query:
                        doc=doc.replace('<div class="drawer" id="folder">','<div class="drawer open" id="folder">')
                    media['srcdoc']=doc; media.pop('src',None)
    return rt

def build(runtime_path: Path):
    cfg=load_json(ROOT/'data/profile.json'); rt=load_json(runtime_path); embedded=_self_contain_runtime(rt)
    tpl=(ROOT/'source/index.html').read_text(encoding='utf-8')
    payload=json.dumps({'config':cfg,'runtime':embedded},ensure_ascii=False).replace('</','<\\/')
    out=tpl.replace('__PROFILE_DATA__',payload)
    build=ROOT/'build'; build.mkdir(exist_ok=True)
    (build/'index.html').write_text(out,encoding='utf-8')
    for name in ['styles.css','app.js']:
        shutil.copy2(ROOT/'source'/name,build/name)
    # Sources needed by demo fallback and live downloaded project covers.
    if (ROOT/'thoth-ui').exists(): shutil.copytree(ROOT/'thoth-ui',build/'thoth-ui',dirs_exist_ok=True)
    if (ROOT/'assets/project-source').exists(): shutil.copytree(ROOT/'assets/project-source',build/'assets/project-source',dirs_exist_ok=True)
    return cfg,rt

def readme(cfg,rt):
    gen='./assets/generated'
    lines=['<!-- GENERATED BY THOTH/FND V3. DO NOT EDIT GENERATED SECTIONS BY HAND. -->','<p align="center"><img src="'+gen+'/hero.gif" alt="THOTH /FND — profile introduction" width="100%"></p>','<p align="center"><img src="'+gen+'/stats.gif" alt="GitHub activity summary" width="100%"></p>']
    for i,p in enumerate(rt.get('projects',[])[:3],1):
        slug=p['slug']; lines.append(f'<p align="center"><img src="{gen}/project-{slug}.gif" alt="{esc(p["name"])} project showcase" width="100%"></p>')
        links=[x for x in p.get('links',[]) if x.get('url')]
        if links:
            btns=[]
            for j,x in enumerate(links[:5]):
                path=f'{gen}/cta-{slug}-{j}.gif'; btns.append(f'<a href="{esc(x["url"])}"><img src="{path}" alt="{esc(x["label"])}" height="34"></a>')
            lines.append('<p align="center">'+' '.join(btns)+'</p>')
    lines.append('<p align="center"><img src="'+gen+'/activity.gif" alt="Development activity and recent commits" width="100%"></p>')
    global_links=[x for x in cfg.get('global_links',[]) if x.get('url')]
    if global_links: lines.append('<p align="center">'+' &nbsp; '.join(f'<a href="{esc(x["url"])}">{esc(x["label"])} ↗</a>' for x in global_links)+'</p>')
    lines.append('')
    (ROOT/'README.md').write_text('\n'.join(lines),encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--runtime',default=str(ROOT/'data/runtime.json')); args=ap.parse_args()
    cfg,rt=build(Path(args.runtime)); readme(cfg,rt)
if __name__=='__main__': main()
